let nome = prompt('Digite seu nome completo: ')
document.body.innerHTML += `seu nome é ${nome} <br />`
document.body.innerHTML += `seu nome tem ${nome.length} letras <br />`
document.body.innerHTML += `a segunda letra do seu nome é ${nome[1]}<br />`
document.body.innerHTML += `qual o primeiro indice da letra a do seu nome? ${nome.indexOf('a')}<br />`
document.body.innerHTML += `qual o ultimo indice da letra a do seu nome? ${nome.lastIndexOf('a')}<br />`
document.body.innerHTML += `as ultimas 3 letras do seu nome são ${nome.slice(-3)}<br />`
document.body.innerHTML += `as palavras do seu nome são: ${nome.split(' ')}<br />`
document.body.innerHTML += `seu nome com letras maiusculas é ${nome.toUpperCase()}<br />`
document.body.innerHTML += `seu nome com letras minusculas é ${nome.toLowerCase()}<br />`
